#!/usr/bin/env bun
import { basename, join } from "node:path";
import { mkdir, stat } from "node:fs/promises";
import { watch as fsWatch } from "node:fs";
import skillBody from "./skill-template.md" with { type: "text" };

const CONFIG = "singlepage.json";
const SCAFFOLD_DIRS = ["public", "server", "cron"];

// --- agent docs --------------------------------------------------------------
// `init` installs a frontend-focused guide for AI coding agents, rendered from a
// single template (src/skill-template.md, embedded in the compiled binary) into
// two targets: a Claude skill (whole file is ours) and a vendor-neutral
// AGENTS.md at the project root (a managed block, so other tooling's content in
// that file is preserved).

const SKILL_DIR = join(".claude", "skills", "singlepage");
const SKILL_FILE = join(SKILL_DIR, "SKILL.md");
const AGENTS_FILE = "AGENTS.md";
const AGENTS_BEGIN = "<!-- BEGIN singlepage (generated by `singlepage init`) -->";
const AGENTS_END = "<!-- END singlepage -->";

const SKILL_FRONTMATTER = `---
name: singlepage
description: Build or edit this Single Page site — static pages in public/, the injected browser client (kv, fn, per-visitor user), server functions in server/, cron jobs, KV visibility classes, and anonymous per-user data. Use whenever changing anything under public/, server/, or cron/, wiring the page to server data, or storing per-visitor state.
---

`;

type SkillVars = { site: string; url: string; endpoint: string };

/** Fill the template's {{SITE}}/{{URL}}/{{ENDPOINT}} placeholders. */
export function renderSkill(template: string, vars: SkillVars): string {
  return template
    .replaceAll("{{SITE}}", vars.site)
    .replaceAll("{{URL}}", vars.url)
    .replaceAll("{{ENDPOINT}}", vars.endpoint);
}

/** The full Claude SKILL.md (frontmatter + rendered body). */
export function buildSkillMd(vars: SkillVars): string {
  return SKILL_FRONTMATTER + renderSkill(skillBody, vars).trim() + "\n";
}

/**
 * Insert or replace our delimited block in an existing AGENTS.md, leaving any
 * surrounding content (other tools' instructions) untouched.
 */
export function upsertAgentsBlock(existing: string, body: string): string {
  const block = `${AGENTS_BEGIN}\n${body.trim()}\n${AGENTS_END}`;
  const start = existing.indexOf(AGENTS_BEGIN);
  const end = existing.indexOf(AGENTS_END);
  let before = existing;
  let after = "";
  if (start !== -1 && end !== -1 && end > start) {
    before = existing.slice(0, start);
    after = existing.slice(end + AGENTS_END.length);
  }
  const parts = [before.replace(/\s+$/, ""), block, after.replace(/^\s+/, "")];
  return parts.filter((p) => p.length > 0).join("\n\n") + "\n";
}

/** Write the Claude skill and upsert the AGENTS.md block for a site. */
async function writeAgentDocs(vars: SkillVars): Promise<void> {
  await mkdir(SKILL_DIR, { recursive: true });
  await Bun.write(SKILL_FILE, buildSkillMd(vars));

  let existing = "";
  try {
    existing = await Bun.file(AGENTS_FILE).text();
  } catch {
    // no AGENTS.md yet — we'll create one
  }
  await Bun.write(AGENTS_FILE, upsertAgentsBlock(existing, renderSkill(skillBody, vars)));
}

// Local secrets, kept OUT of singlepage.json (which is synced to the server) and
// gitignored. Holds the admin token (site creation + key rotation) and this
// site's deploy key (file uploads). Never uploaded.
const CREDS = ".singlepage.credentials.json";
type Creds = { adminToken?: string; deployKey?: string };

async function loadCreds(): Promise<Creds> {
  try {
    return (await Bun.file(CREDS).json()) as Creds;
  } catch {
    return {}; // no credentials file yet
  }
}

async function saveCreds(creds: Creds): Promise<void> {
  await Bun.write(CREDS, JSON.stringify(creds, null, 2) + "\n");
  await ensureGitignored(CREDS);
}

/** Append `entry` to ./.gitignore if not already present (creating it if absent). */
async function ensureGitignored(entry: string): Promise<void> {
  let contents = "";
  try {
    contents = await Bun.file(".gitignore").text();
  } catch {
    // no .gitignore yet — we'll create one
  }
  if (contents.split("\n").some((l) => l.trim() === entry)) return;
  const prefix = contents && !contents.endsWith("\n") ? "\n" : "";
  await Bun.write(".gitignore", contents + prefix + entry + "\n");
}

// Admin token authorizes site creation + deploy-key rotation; the deploy key
// authorizes file uploads for one site. Credentials file wins, env is a fallback.
const resolveAdminToken = (creds: Creds): string | undefined =>
  creds.adminToken ?? process.env.SINGLEPAGE_APP_TOKEN;
const resolveDeployKey = (creds: Creds): string | undefined =>
  creds.deployKey ?? process.env.SINGLEPAGE_DEPLOY_KEY;

const bearerHeaders = (token: string): Record<string, string> => ({
  authorization: `Bearer ${token}`,
});

// Header set used for file uploads/deletes; populated with the deploy key in watch().
let fileAuthHeaders: Record<string, string> = {};
const authHeaders = (): Record<string, string> => fileAuthHeaders;

// `watch` syncs these dirs plus a few site-root files: the config (server needs
// cron config) and `.env` (the site's secrets, exposed to server/cron as
// ctx.env; stored server-side outside public/, so never served).
const SYNC_DIRS = SCAFFOLD_DIRS;
const ENV_FILE = ".env";
const EXTRA_FILES = [CONFIG, ENV_FILE];
const DEBOUNCE_MS = 150;   // collapse a burst of fs events into one reconcile
const RECONCILE_MS = 2000; // periodic safety-net rescan
const MAX_CONCURRENT = 8;

type Config = { endpoint: string; site: string; url?: string };

// --- init ------------------------------------------------------------------

async function init() {
  const creds = await loadCreds();
  const adminToken = resolveAdminToken(creds);
  if (!adminToken) {
    console.error(
      "An admin token is required to create a site. Set SINGLEPAGE_APP_TOKEN (e.g. in a .env file) and retry.",
    );
    process.exit(1);
  }

  // Reuse a previously saved endpoint as the default, if present.
  let prev: { endpoint?: string } = {};
  try {
    prev = await Bun.file(CONFIG).json();
  } catch {
    // no existing config — that's fine
  }
  const defaultEndpoint = prev.endpoint ?? "http://localhost";

  const answer = prompt(`Single Page API endpoint [${defaultEndpoint}]:`)?.trim();
  const endpoint = (answer || defaultEndpoint).replace(/\/+$/, "");
  if (!endpoint) {
    console.error("No endpoint provided. Aborting.");
    process.exit(1);
  }

  const dirName = basename(process.cwd());

  let res: Response;
  try {
    res = await fetch(`${endpoint}/api/sites`, {
      method: "POST",
      headers: { "content-type": "application/json", ...bearerHeaders(adminToken) },
      body: JSON.stringify({ name: dirName }),
    });
  } catch (err) {
    console.error(`Could not reach ${endpoint}: ${(err as Error).message}`);
    process.exit(1);
  }

  if (res.status === 401) {
    console.error("Unauthorized — the admin token (SINGLEPAGE_APP_TOKEN) doesn't match the server.");
    process.exit(1);
  }
  if (!res.ok) {
    console.error(`Server error ${res.status}: ${await res.text()}`);
    process.exit(1);
  }

  const site = (await res.json()) as { name: string; url: string; deployKey: string };
  // Persist `url` too: it's the site's public address, used to render the agent
  // guide's header. Storing it lets `regen-docs` rebuild the guide later without
  // re-contacting the server.
  const config = { endpoint, site: site.name, url: site.url, cron: {} as Record<string, string> };
  await Bun.write(CONFIG, JSON.stringify(config, null, 2) + "\n");
  // Persist both secrets locally (gitignored, never synced).
  await saveCreds({ adminToken, deployKey: site.deployKey });

  // Scaffold local project directories (idempotent).
  for (const dir of SCAFFOLD_DIRS) {
    await mkdir(dir, { recursive: true });
  }

  // Seed a gitignored `.env` for site secrets (API keys etc.), exposed to
  // server/cron code as ctx.env. Never clobber an existing one.
  await ensureGitignored(ENV_FILE);
  if (!(await Bun.file(ENV_FILE).exists())) {
    await Bun.write(
      ENV_FILE,
      "# Site secrets for server/ and cron/ code, read as ctx.env.NAME\n" +
        "# Synced to the server (never served to the browser). Keep only\n" +
        "# site secrets here — NOT SINGLEPAGE_* operator tokens.\n" +
        "# EXAMPLE_API_KEY=your-key-here\n",
    );
  }

  // Install the agent guide (Claude skill + neutral AGENTS.md) for this site.
  await writeAgentDocs({ site: site.name, url: site.url, endpoint });

  console.log(`\n✓ Created site "${site.name}"`);
  console.log(`  URL:         ${site.url}`);
  console.log(`  Config:      ./${CONFIG}`);
  console.log(`  Credentials: ./${CREDS} (gitignored — keep it secret)`);
  console.log(`  Secrets:     ./${ENV_FILE} (gitignored — site secrets, read as ctx.env)`);
  console.log(`  Dirs:        ${SCAFFOLD_DIRS.map((d) => `${d}/`).join("  ")}`);
  console.log(`  Agent guide: ./${SKILL_FILE}  +  ./${AGENTS_FILE}`);
}

// --- rotate-key -------------------------------------------------------------

async function rotateKey() {
  const cfg = await loadConfig();
  const creds = await loadCreds();
  const adminToken = resolveAdminToken(creds);
  if (!adminToken) {
    console.error(
      "An admin token is required to rotate a deploy key. Set SINGLEPAGE_APP_TOKEN and retry.",
    );
    process.exit(1);
  }

  let res: Response;
  try {
    res = await fetch(`${cfg.endpoint}/api/sites/${encodeURIComponent(cfg.site)}/deploy-key`, {
      method: "POST",
      headers: bearerHeaders(adminToken),
    });
  } catch (err) {
    console.error(`Could not reach ${cfg.endpoint}: ${(err as Error).message}`);
    process.exit(1);
  }

  if (res.status === 401) {
    console.error("Unauthorized — the admin token (SINGLEPAGE_APP_TOKEN) doesn't match the server.");
    process.exit(1);
  }
  if (!res.ok) {
    console.error(`Server error ${res.status}: ${await res.text()}`);
    process.exit(1);
  }

  const { deployKey } = (await res.json()) as { deployKey: string };
  await saveCreds({ ...creds, adminToken, deployKey });
  console.log(`\n✓ Rotated deploy key for "${cfg.site}".`);
  console.log(`  Saved to ./${CREDS}. The previous key no longer works.`);
}

// --- shared helpers ---------------------------------------------------------

async function loadConfig(): Promise<Config> {
  let cfg: { endpoint?: string; site?: string; url?: string };
  try {
    cfg = await Bun.file(CONFIG).json();
  } catch {
    console.error(`No ${CONFIG} found here. Run \`singlepage init\` first.`);
    process.exit(1);
  }
  if (!cfg?.endpoint || !cfg?.site) {
    console.error(`${CONFIG} is missing "endpoint" or "site". Run \`singlepage init\`.`);
    process.exit(1);
  }
  return {
    endpoint: String(cfg.endpoint).replace(/\/+$/, ""),
    site: String(cfg.site),
    // `url` was added later; older configs won't have it (see regen-docs fallback).
    ...(cfg.url ? { url: String(cfg.url) } : {}),
  };
}

// --- regen-docs ------------------------------------------------------------

// Re-render the agent guide (Claude SKILL.md + the AGENTS.md block) from the
// current binary's embedded template, using the existing project's config. No
// server call, no credentials, no new site — just the local docs. Run it after
// upgrading the CLI so a project scaffolded by an older binary picks up template
// changes (e.g. newly documented features).
async function regenDocs() {
  const cfg = await loadConfig();
  // `url` is only used in the guide's header line and wasn't persisted by older
  // `init`s; fall back to the endpoint so pre-existing projects still regenerate.
  const url = cfg.url ?? cfg.endpoint;
  await writeAgentDocs({ site: cfg.site, url, endpoint: cfg.endpoint });
  console.log(`✓ Regenerated agent guide for "${cfg.site}"`);
  console.log(`  Skill:  ./${SKILL_FILE}`);
  console.log(`  Agents: ./${AGENTS_FILE}`);
}

/** Bounds the number of concurrent transfers in flight. */
function makeSemaphore(max: number) {
  let active = 0;
  const queue: (() => void)[] = [];
  return async function run<T>(fn: () => Promise<T>): Promise<T> {
    if (active >= max) await new Promise<void>((r) => queue.push(r));
    active++;
    try {
      return await fn();
    } finally {
      active--;
      queue.shift()?.();
    }
  };
}

function fileUrl({ endpoint, site }: Config, relpath: string): string {
  return `${endpoint}/api/sites/${encodeURIComponent(site)}/files?path=${encodeURIComponent(relpath)}`;
}

/**
 * The site `.env` is uploaded and exposed to server/cron code as ctx.env, so
 * operator-only vars (the admin token, deploy key — anything the server reads
 * from its OWN environment) must never live there. Refuse to sync a `.env` that
 * carries a SINGLEPAGE_* var and point the user at the credentials file instead.
 * Returns true (with a warning) when the file should be skipped.
 */
async function envSyncBlocked(relpath: string): Promise<boolean> {
  if (relpath !== ENV_FILE) return false;
  let text: string;
  try {
    text = await Bun.file(relpath).text();
  } catch {
    return false; // vanished — let the normal delete path handle it
  }
  const bad = text
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => /^(export\s+)?SINGLEPAGE_[A-Za-z0-9_]*\s*=/.test(l))
    .map((l) => l.replace(/^export\s+/, "").split("=")[0]!.trim());
  if (bad.length === 0) return false;
  console.error(
    `  ✗ refusing to sync ${ENV_FILE} — it defines operator vars that would leak to the site:\n` +
      bad.map((n) => `      ${n}`).join("\n") +
      `\n    Move SINGLEPAGE_* out of ${ENV_FILE} (use ./${CREDS} or your shell env); keep only site secrets in ${ENV_FILE}.`,
  );
  return true;
}

async function uploadPath(cfg: Config, relpath: string): Promise<boolean> {
  // Skip (but treat as reconciled) an unsafe .env so we don't retry-spam.
  if (await envSyncBlocked(relpath)) return true;
  try {
    const res = await fetch(fileUrl(cfg, relpath), {
      method: "PUT",
      headers: authHeaders(),
      body: Bun.file(relpath),
    });
    if (!res.ok) {
      console.error(`  ✗ upload ${relpath} → ${res.status}`);
      return false;
    }
    console.log(`  ↑ ${relpath}`);
    return true;
  } catch (err) {
    console.error(`  ✗ upload ${relpath} → ${(err as Error).message}`);
    return false;
  }
}

async function deletePath(cfg: Config, relpath: string): Promise<boolean> {
  try {
    const res = await fetch(fileUrl(cfg, relpath), {
      method: "DELETE",
      headers: authHeaders(),
    });
    if (!res.ok) {
      console.error(`  ✗ delete ${relpath} → ${res.status}`);
      return false;
    }
    console.log(`  ✗ ${relpath} (deleted)`);
    return true;
  } catch (err) {
    console.error(`  ✗ delete ${relpath} → ${(err as Error).message}`);
    return false;
  }
}

/**
 * Snapshot of every synced file -> a cheap change signature (mtime:size).
 * Used both as the initial upload set and as the baseline for reconcile diffs.
 */
async function snapshotFiles(): Promise<Map<string, string>> {
  const map = new Map<string, string>();
  const add = async (rel: string) => {
    try {
      const s = await stat(rel);
      if (s.isFile()) map.set(rel, `${s.mtimeMs}:${s.size}`);
    } catch {
      // vanished between scan and stat — skip
    }
  };
  for (const dir of SYNC_DIRS) {
    const glob = new Bun.Glob("**/*");
    for await (const rel of glob.scan({ cwd: dir, onlyFiles: true })) {
      await add(`${dir}/${rel}`);
    }
  }
  for (const f of EXTRA_FILES) await add(f);
  return map;
}

// --- watch ------------------------------------------------------------------

async function watch() {
  const cfg = await loadConfig();
  const deployKey = resolveDeployKey(await loadCreds());
  if (!deployKey) {
    console.error(
      `No deploy key found. Run \`singlepage init\` (new site) or \`singlepage rotate-key\` (existing site) to issue one.`,
    );
    process.exit(1);
  }
  fileAuthHeaders = bearerHeaders(deployKey);
  const sem = makeSemaphore(MAX_CONCURRENT);

  // 1) Initial full upload. The snapshot is the post-upload baseline, so the
  //    first reconcile sees no diff and we don't re-upload everything.
  let snapshot = await snapshotFiles();
  const files = [...snapshot.keys()];
  console.log(`Uploading ${files.length} file(s) to ${cfg.endpoint} (site "${cfg.site}")...`);
  await Promise.all(files.map((rel) => sem(() => uploadPath(cfg, rel))));

  // 2) Per-path worker — serializes transfers for a single path so overlapping
  //    edits never produce out-of-order PUTs; each pass re-derives the action
  //    from current FS state, so the latest write always wins.
  const dirty = new Set<string>();   // paths needing sync
  const running = new Set<string>(); // paths with an active worker

  async function pump(rel: string) {
    if (running.has(rel)) return;
    running.add(rel);
    try {
      while (dirty.has(rel)) {
        dirty.delete(rel);

        let sig: string | null = null; // non-null => file exists, upload it
        try {
          const s = await stat(rel);
          if (s.isDirectory()) continue; // dir events carry no content
          sig = `${s.mtimeMs}:${s.size}`;
        } catch (err) {
          if ((err as NodeJS.ErrnoException).code !== "ENOENT") {
            console.error(`  ! stat ${rel}: ${(err as Error).message}`);
            continue;
          }
        }

        const ok = await sem(() =>
          sig !== null ? uploadPath(cfg, rel) : deletePath(cfg, rel),
        );
        // Only advance the baseline on success; failures stay diffed so the
        // next reconcile retries them automatically.
        if (ok) {
          if (sig !== null) snapshot.set(rel, sig);
          else snapshot.delete(rel);
        }
      }
    } finally {
      running.delete(rel);
    }
  }

  // 3) Reconcile is the source of truth: rescan, diff against the baseline, and
  //    pump anything that differs. This catches what fs.watch misses on macOS
  //    (files in newly-created subdirectories, coalesced burst events).
  async function reconcile() {
    const cur = await snapshotFiles();
    for (const [rel, sig] of cur) {
      if (snapshot.get(rel) !== sig) {
        dirty.add(rel);
        void pump(rel);
      }
    }
    for (const rel of snapshot.keys()) {
      if (!cur.has(rel)) {
        dirty.add(rel); // deleted locally
        void pump(rel);
      }
    }
  }

  // fs.watch is only a low-latency trigger; reconcile does the real work.
  let pending: ReturnType<typeof setTimeout> | null = null;
  const triggerReconcile = () => {
    if (pending) return;
    pending = setTimeout(() => {
      pending = null;
      void reconcile();
    }, DEBOUNCE_MS);
  };

  const watchers: ReturnType<typeof fsWatch>[] = [];
  for (const dir of SYNC_DIRS) {
    try {
      watchers.push(fsWatch(dir, { recursive: true }, () => triggerReconcile()));
    } catch (err) {
      console.error(`Cannot watch ${dir}/: ${(err as Error).message}`);
    }
  }
  for (const f of EXTRA_FILES) {
    try {
      watchers.push(fsWatch(f, () => triggerReconcile()));
    } catch {
      // the file may not exist yet — reconcile's rescan will pick it up later
    }
  }

  // Periodic safety-net rescan in case an fs event never arrives.
  const sweep = setInterval(() => void reconcile(), RECONCILE_MS);

  process.on("SIGINT", () => {
    console.log("\nStopping watch.");
    clearInterval(sweep);
    for (const w of watchers) w.close();
    process.exit(0);
  });

  console.log(
    `\nWatching ${SYNC_DIRS.map((d) => `${d}/`).join(", ")} and ${EXTRA_FILES.join(", ")} — Ctrl-C to stop.`,
  );
}

// --- dispatch ---------------------------------------------------------------

// Only dispatch when run directly (so tests can import the helpers above).
if (import.meta.main) {
  const cmd = process.argv[2];
  if (cmd === "init") {
    await init();
  } else if (cmd === "watch") {
    await watch();
  } else if (cmd === "rotate-key") {
    await rotateKey();
  } else if (cmd === "regen-docs") {
    await regenDocs();
  } else {
    console.log("Usage: singlepage <init|watch|rotate-key|regen-docs>");
    process.exit(cmd ? 1 : 0);
  }
}
