import { test, expect } from "bun:test";
import { renderSkill, buildSkillMd, upsertAgentsBlock } from "./cli.ts";

const VARS = {
  site: "my-site",
  url: "http://my-site.localhost:3000/",
  endpoint: "http://localhost:3000",
};

test("renderSkill substitutes every placeholder", () => {
  const out = renderSkill("site {{SITE}} at {{URL}} via {{ENDPOINT}}", VARS);
  expect(out).toBe("site my-site at http://my-site.localhost:3000/ via http://localhost:3000");
  expect(out).not.toContain("{{");
});

test("buildSkillMd renders the bundled template with project values", () => {
  const md = buildSkillMd(VARS);
  // No unrendered placeholders survive.
  expect(md).not.toContain("{{");
  // Project header is personalized.
  expect(md).toContain("my-site");
  expect(md).toContain("http://my-site.localhost:3000/");
  // Frontend surfaces are documented; backend internals are not the focus.
  for (const section of ["public/", "server/", "cron/", "kv", "fn", "private", "readonly", "readwrite"]) {
    expect(md).toContain(section);
  }
});

test("buildSkillMd starts with valid frontmatter naming the skill", () => {
  const md = buildSkillMd(VARS);
  expect(md.startsWith("---\n")).toBe(true);
  const fm = md.slice(4, md.indexOf("\n---", 4));
  expect(fm).toContain("name: singlepage");
  expect(fm).toContain("description:");
});

test("upsertAgentsBlock creates a delimited block when none exists", () => {
  const out = upsertAgentsBlock("", "body text");
  expect(out).toContain("<!-- BEGIN singlepage");
  expect(out).toContain("body text");
  expect(out).toContain("<!-- END singlepage -->");
  expect(out.endsWith("\n")).toBe(true);
});

test("upsertAgentsBlock replaces only its own block, preserving other content", () => {
  const existing = [
    "# My project notes",
    "",
    "Some instructions for other tools.",
    "",
    "<!-- BEGIN singlepage (generated by `singlepage init`) -->",
    "OLD body",
    "<!-- END singlepage -->",
    "",
    "Trailing notes that must survive.",
  ].join("\n");

  const out = upsertAgentsBlock(existing, "NEW body");

  expect(out).toContain("# My project notes");
  expect(out).toContain("Some instructions for other tools.");
  expect(out).toContain("Trailing notes that must survive.");
  expect(out).toContain("NEW body");
  expect(out).not.toContain("OLD body");
  // Exactly one managed block remains.
  expect(out.split("<!-- BEGIN singlepage").length - 1).toBe(1);
  expect(out.split("<!-- END singlepage -->").length - 1).toBe(1);
});

test("upsertAgentsBlock appends after existing non-managed content", () => {
  const existing = "# Existing AGENTS.md\n\nrules here";
  const out = upsertAgentsBlock(existing, "our body");
  expect(out.indexOf("rules here")).toBeLessThan(out.indexOf("our body"));
  expect(out).toContain("<!-- BEGIN singlepage");
});
